path:
  ckpt_path: "./output/ckpt"
  log_path: "./output/log"
  result_path: "./output/result"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 500
  synth_step: 1000
  val_step: 5000
  save_step: 5000
